name: CI/CD for Stock Trading AI with SQLite Deployment on Azure Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  tests:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "FMP_API_KEY=${{ secrets.FMP_API_KEY }}" >> $GITHUB_ENV
          echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" >> $GITHUB_ENV

      - name: Create Temporary .env File
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "FMP_API_KEY=${{ secrets.FMP_API_KEY }}" >> .env
          echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" >> .env

      - name: Run Pytest
        run: |
          pytest -v tests/ | tee log_tests.txt
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest_results
          path: log_tests.txt

      - name: Cleanup .env File
        if: always()
        run: rm -f .env
